Julia 0.4 compatability
Adds Julia 0.4 compatability whilst maintaining Julia 0.3 compatability using the Compat package.

Also changes all Ptr{None} (renamed in 0.4 to Ptr{Union{}}) to Ptr{Void}. Ptr{None} is used in none of my installed packages, and seemed to be giving problems:
julia> convert(Union(), 1)
ERROR: StackOverflowError:
 in convert at ./dates/periods.jl:22